/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import static VentanasEmergentes.agregarMetodosPago.crearAgregarMetodosPago;
import static VentanasEmergentes.agregarMonedas.crearMoneda;
import inventario.ObtenerParametros;
import java.awt.Color;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class ajustes extends javax.swing.JPanel {

    /**
     * Creates new form ajustes
     */
    ObtenerParametros parametros;
    String nombre, direccion, rif;
    int iva, ganancia; 
    double tasa;
    boolean activo;
    boolean dia;
    LocalDate fechaPC = LocalDate.now();
    LocalDate fechaSistema;
    AlmacenJframe ventanaPrincipal;
    private final DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    
    public ajustes(ObtenerParametros parametros, AlmacenJframe ventanaPrincipal) {
        this.parametros = parametros;
        this.ventanaPrincipal = ventanaPrincipal;
        datos();
        initComponents();
        fechaPcLabel.setText(fechaPC.format(formato));
        fechaProgramaLabel.setText(fechaSistema.format(formato));
        errorTasaLabel.setVisible(false);
        
        if(!activo){
            activoBoton.setBackground(Color.red);
            activoBoton.setText("Inactivo");    
        }
        if(!dia){
            diaBoton.setBackground(Color.red);
            diaBoton.setText("Iniciar día");
            diaLabel.setText("Sin iniciar");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
    ObtenerParametros parametros;
    String nombre, direccion, rif;
    int tasa, iva, ganancia; 
    public ajustes(ObtenerParametros parametros) {
        parametros = this.parametros;
        datos();
        initComponents();
    }

    /**
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardarBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JTextField();
        direccionTexto = new javax.swing.JTextField();
        rifTexto = new javax.swing.JTextField();
        tasaTexto = new javax.swing.JTextField();
        ivaTexto = new javax.swing.JTextField();
        gananciaTexto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        activoBoton = new javax.swing.JButton();
        errorTasaLabel = new javax.swing.JLabel();
        SalirBoton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fechaProgramaLabel = new javax.swing.JLabel();
        diaLabel = new javax.swing.JLabel();
        fechaPcLabel = new javax.swing.JLabel();
        diaBoton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        activoBoton1 = new javax.swing.JButton();
        activoBoton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("ajustes"); // NOI18N
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        guardarBoton.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        guardarBoton.setText("Guardar");
        guardarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarBotonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel1.setText("Nombre del negocio");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel2.setText("Dirección");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel3.setText("RIF");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel4.setText("Tasa de cambio");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel5.setText("IVA por defecto");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel6.setText("Porcentaje de ganancia por defecto:");

        nombreTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        nombreTexto.setText(nombre);
        nombreTexto.setNextFocusableComponent(direccionTexto);

        direccionTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        direccionTexto.setText(direccion);
        direccionTexto.setNextFocusableComponent(rifTexto);

        rifTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        rifTexto.setText(rif);
        rifTexto.setNextFocusableComponent(tasaTexto);

        tasaTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        tasaTexto.setText(String.valueOf(tasa));
        tasaTexto.setNextFocusableComponent(ivaTexto);

        ivaTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        ivaTexto.setText(String.valueOf(iva));
        ivaTexto.setNextFocusableComponent(gananciaTexto);

        gananciaTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        gananciaTexto.setText(String.valueOf(ganancia));
        gananciaTexto.setNextFocusableComponent(guardarBoton);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel7.setText("Tasa automatica:");

        activoBoton.setBackground(new java.awt.Color(0, 153, 0));
        activoBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        activoBoton.setText("Activo");
        activoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoBotonActionPerformed(evt);
            }
        });

        errorTasaLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        errorTasaLabel.setForeground(new java.awt.Color(204, 0, 0));
        errorTasaLabel.setText("Ha ocurrido un error al cargar la tasa");

        SalirBoton.setBackground(new java.awt.Color(255, 0, 51));
        SalirBoton.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        SalirBoton.setText("Salir");
        SalirBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirBotonMouseClicked(evt);
            }
        });
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jLabel12.setText("Estado del dia:");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jLabel13.setText("Fecha del programa:");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jLabel14.setText("Fecha del PC:");

        fechaProgramaLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        fechaProgramaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaProgramaLabel.setText("Sin Iniciar");

        diaLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        diaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diaLabel.setText("Iniciado");

        fechaPcLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        fechaPcLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaPcLabel.setText("Sin Iniciar");

        diaBoton.setBackground(new java.awt.Color(0, 153, 0));
        diaBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        diaBoton.setText("Iniciado");
        diaBoton.setName("diaBoton"); // NOI18N
        diaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaBotonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel8.setText("Métodos de pago:");

        activoBoton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        activoBoton1.setText("Agregar");
        activoBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoBoton1ActionPerformed(evt);
            }
        });

        activoBoton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        activoBoton2.setText("Agregar");
        activoBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activoBoton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel9.setText("Agregar monedas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SalirBoton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(direccionTexto)
                                .addComponent(rifTexto)
                                .addComponent(tasaTexto)
                                .addComponent(ivaTexto)
                                .addComponent(gananciaTexto)
                                .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(diaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 33, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fechaProgramaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(fechaPcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(diaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(activoBoton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(activoBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(activoBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))))
                            .addComponent(guardarBoton)
                            .addComponent(errorTasaLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaProgramaLabel)
                    .addComponent(fechaPcLabel)
                    .addComponent(diaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rifTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tasaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ivaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gananciaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(activoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activoBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(activoBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorTasaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SalirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    //Extrae los datos almacenados en el archivo de texto "Datos.txt"
    private void datos(){
        nombre = parametros.getNombre();
        direccion = parametros.getDireccion();
        rif = parametros.getRif();
        tasa = parametros.getTasa();
        iva = parametros.getIva();
        ganancia = parametros.getGanancia();
        activo = parametros.isActivo();
        dia = parametros.isDia();
        fechaSistema = parametros.getFecha();
    }

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        
    }//GEN-LAST:event_formAncestorAdded

    private void guardarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBotonMouseClicked
        try{
            parametros.setNombre(nombreTexto.getText());
            parametros.setDireccion(direccionTexto.getText());
            parametros.setRif(rifTexto.getText());
            parametros.setTasa(Double.parseDouble(tasaTexto.getText()));
            parametros.setIva(Integer.parseInt(ivaTexto.getText()));
            parametros.setGanancia(Integer.parseInt(gananciaTexto.getText()));
            parametros.setActivo(activo);
            parametros.guardar();
            if(activo){
                errorTasaLabel.setVisible(!parametros.isErrorTasa());
            }

        }
        catch(IOException | NumberFormatException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_guardarBotonMouseClicked

    private void activoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoBotonActionPerformed
        if(activoBoton.getBackground() == Color.red){
            activoBoton.setBackground(Color.green);
            activoBoton.setText("Activo");   
            activo = true;
            System.out.println(activo);
        }
        else{
            activoBoton.setBackground(Color.red);
            activoBoton.setText("Inactivo"); 
            errorTasaLabel.setVisible(false);
            activo = false;
            System.out.println(activo);
        }
    }//GEN-LAST:event_activoBotonActionPerformed

    private void SalirBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirBotonMouseClicked

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed

    private void diaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaBotonActionPerformed
        if(diaBoton.getBackground() == Color.red){
            if(fechaPC.equals(fechaSistema)){
                JOptionPane.showMessageDialog(null, "Este día ya ha sido cerrado");
            }
            else{
                diaBoton.setBackground(Color.green);
                diaBoton.setText("Iniciado");  
                diaLabel.setText("Iniciado");
                dia = true;
                parametros.setDia(dia);
                System.out.println(dia);
                fechaProgramaLabel.setText(fechaPcLabel.getText());
                ventanaPrincipal.setDateDiaLabel(fechaPC);
                ventanaPrincipal.iniciarDia(dia);
                fechaSistema = fechaPC;
                parametros.setFecha(fechaPC);
            }
        }
        else{
            if (fechaPC.equals(fechaSistema)) {
    int respuesta = JOptionPane.showConfirmDialog(
        null, 
        "Una vez finalizado el día no se podrá iniciar hasta mañana\n¿Aún desea finalizar el día?", 
        "Finalizar día", 
        JOptionPane.YES_NO_OPTION
    );
    
    // Si el usuario NO confirma (NO o Cierra el diálogo), salimos sin hacer nada
    if (respuesta != 0) {
        return; // o continuar con otro flujo si es necesario
    }
}

        diaBoton.setBackground(Color.red);
        diaBoton.setText("Iniciar"); 
        diaLabel.setText("Sin iniciar");
        errorTasaLabel.setVisible(false);
        dia = false;
        parametros.setDia(dia);
        ventanaPrincipal.iniciarDia(dia);
        }
        try {
            parametros.guardar();
        } catch (IOException ex) {
            Logger.getLogger(ajustes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_diaBotonActionPerformed

    private void activoBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoBoton1ActionPerformed
        crearAgregarMetodosPago(null);
    }//GEN-LAST:event_activoBoton1ActionPerformed

    private void activoBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activoBoton2ActionPerformed
        crearMoneda(null);
    }//GEN-LAST:event_activoBoton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalirBoton;
    private javax.swing.JButton activoBoton;
    private javax.swing.JButton activoBoton1;
    private javax.swing.JButton activoBoton2;
    private javax.swing.JButton diaBoton;
    private javax.swing.JLabel diaLabel;
    private javax.swing.JTextField direccionTexto;
    private javax.swing.JLabel errorTasaLabel;
    private javax.swing.JLabel fechaPcLabel;
    private javax.swing.JLabel fechaProgramaLabel;
    private javax.swing.JTextField gananciaTexto;
    private javax.swing.JButton guardarBoton;
    private javax.swing.JTextField ivaTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JTextField rifTexto;
    private javax.swing.JTextField tasaTexto;
    // End of variables declaration//GEN-END:variables
}
