package ventanas;
import inventario.DepartamentoBD;
import inventario.ObtenerParametros;
import inventario.ProductosBD;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static ventanas.LoginID.cargarLogin;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author angel
 */
public class AlmacenJframe extends javax.swing.JFrame{

    /**
     * Creates new form AlmacenJframe
     */
    
    Connection conexion;
    boolean gananciaUltimo;
    boolean ivaUltimo;
    double gananciaDefecto = 0;
    double ivaDefecto = 0;
    double precioFinalUltimo;
    DefaultTableModel modelo;
    DefaultTableModel modeloProductos;
    productosPanel panelProductos;
    ventasPanel ventasPanel;
    JPanel ultimoPanel;
    ajustes ajustess;
    Usuarios usuarios;
    inicioPanel panelInicio;
    ventasPanel panelVentas;
    ObtenerParametros parametros;
    LocalDate fecha;
    private final DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    
    
    public AlmacenJframe(Connection con, String nombre) {
        conexion = con;
        parametros = new ObtenerParametros();
        initComponents();
        fechaLabel.setText(parametros.getFecha().format(formato));
        iniciarDia(parametros.isDia());
        if(!nombre.equals("Ventas")){
            panelInicio = new inicioPanel();
            Paneles.add(panelInicio);
        }
        else{
            panelVentas = new ventasPanel(conexion, parametros);
            Paneles.add(panelVentas);
            this.remove(barraSuperior);
        }
        ultimoPanel = panelInicio;
        System.out.println(fecha.now());
    }
    
    public static void iniciarAlmacen(Connection con, String nombre){
        try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(AlmacenJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new AlmacenJframe(con, nombre).setVisible(true);
                }
            });
            
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        Paneles = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        barraSuperior = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        diaLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        botonInicio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        botonProductos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonVentas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonClientes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        botonReportes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        botonProveedores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        botonAjustes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        botonCambiar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setExtendedState(this.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(1214, 820));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setLayout(new java.awt.BorderLayout());

        Paneles.setBackground(new java.awt.Color(204, 204, 255));
        Paneles.setLayout(new javax.swing.BoxLayout(Paneles, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(Paneles, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(670, 70));
        jPanel1.setLayout(new java.awt.BorderLayout());

        barraSuperior.setBackground(new java.awt.Color(0, 51, 0));
        barraSuperior.setMinimumSize(new java.awt.Dimension(1214, 820));
        barraSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));
        jPanel3.setToolTipText("");
        jPanel3.setName("diaPanel"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 50));

        diaLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        diaLabel.setForeground(new java.awt.Color(255, 255, 255));
        diaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diaLabel.setText("Día sin iniciar");

        fechaLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaLabel.setText("18-02-2005");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(diaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fechaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(diaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        barraSuperior.add(jPanel3);
        jPanel3.getAccessibleContext().setAccessibleName("");

        botonInicio.setBackground(new java.awt.Color(0, 102, 0));
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonInicio.setName("botonAjustes"); // NOI18N
        botonInicio.setPreferredSize(new java.awt.Dimension(100, 50));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Inicio");

        javax.swing.GroupLayout botonInicioLayout = new javax.swing.GroupLayout(botonInicio);
        botonInicio.setLayout(botonInicioLayout);
        botonInicioLayout.setHorizontalGroup(
            botonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(botonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonInicioLayout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 28, Short.MAX_VALUE)))
        );
        botonInicioLayout.setVerticalGroup(
            botonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(botonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonInicioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        barraSuperior.add(botonInicio);

        botonProductos.setBackground(new java.awt.Color(0, 102, 0));
        botonProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonProductos.setPreferredSize(new java.awt.Dimension(100, 50));
        botonProductos.setVerifyInputWhenFocusTarget(false);
        botonProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonProductosMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventario");

        javax.swing.GroupLayout botonProductosLayout = new javax.swing.GroupLayout(botonProductos);
        botonProductos.setLayout(botonProductosLayout);
        botonProductosLayout.setHorizontalGroup(
            botonProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
            .addGroup(botonProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonProductosLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        botonProductosLayout.setVerticalGroup(
            botonProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(botonProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonProductosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        barraSuperior.add(botonProductos);

        botonVentas.setBackground(new java.awt.Color(0, 102, 0));
        botonVentas.setName("botonVentas"); // NOI18N
        botonVentas.setPreferredSize(new java.awt.Dimension(100, 50));
        botonVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonVentasMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ventas");

        javax.swing.GroupLayout botonVentasLayout = new javax.swing.GroupLayout(botonVentas);
        botonVentas.setLayout(botonVentasLayout);
        botonVentasLayout.setHorizontalGroup(
            botonVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(botonVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonVentasLayout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 22, Short.MAX_VALUE)))
        );
        botonVentasLayout.setVerticalGroup(
            botonVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(botonVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonVentasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        barraSuperior.add(botonVentas);

        botonClientes.setBackground(new java.awt.Color(0, 102, 0));
        botonClientes.setName("botonVentas"); // NOI18N
        botonClientes.setPreferredSize(new java.awt.Dimension(100, 50));
        botonClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonClientesMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Clientes");

        javax.swing.GroupLayout botonClientesLayout = new javax.swing.GroupLayout(botonClientes);
        botonClientes.setLayout(botonClientesLayout);
        botonClientesLayout.setHorizontalGroup(
            botonClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(botonClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonClientesLayout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );
        botonClientesLayout.setVerticalGroup(
            botonClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(botonClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonClientesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        barraSuperior.add(botonClientes);

        botonReportes.setBackground(new java.awt.Color(0, 102, 0));
        botonReportes.setName("botonVentas"); // NOI18N
        botonReportes.setPreferredSize(new java.awt.Dimension(100, 50));
        botonReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonReportesMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reportes");

        javax.swing.GroupLayout botonReportesLayout = new javax.swing.GroupLayout(botonReportes);
        botonReportes.setLayout(botonReportesLayout);
        botonReportesLayout.setHorizontalGroup(
            botonReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(botonReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonReportesLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 13, Short.MAX_VALUE)))
        );
        botonReportesLayout.setVerticalGroup(
            botonReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(botonReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonReportesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        barraSuperior.add(botonReportes);

        botonProveedores.setBackground(new java.awt.Color(0, 102, 0));
        botonProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonProveedores.setName("botonAjustes"); // NOI18N
        botonProveedores.setPreferredSize(new java.awt.Dimension(100, 50));
        botonProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonProveedoresMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Proveedores");

        javax.swing.GroupLayout botonProveedoresLayout = new javax.swing.GroupLayout(botonProveedores);
        botonProveedores.setLayout(botonProveedoresLayout);
        botonProveedoresLayout.setHorizontalGroup(
            botonProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(botonProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonProveedoresLayout.createSequentialGroup()
                    .addGap(0, 3, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        botonProveedoresLayout.setVerticalGroup(
            botonProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(botonProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonProveedoresLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        barraSuperior.add(botonProveedores);

        botonAjustes.setBackground(new java.awt.Color(0, 102, 0));
        botonAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonAjustes.setName("botonAjustes"); // NOI18N
        botonAjustes.setPreferredSize(new java.awt.Dimension(100, 50));
        botonAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAjustesMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ajustes");

        javax.swing.GroupLayout botonAjustesLayout = new javax.swing.GroupLayout(botonAjustes);
        botonAjustes.setLayout(botonAjustesLayout);
        botonAjustesLayout.setHorizontalGroup(
            botonAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(botonAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonAjustesLayout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 20, Short.MAX_VALUE)))
        );
        botonAjustesLayout.setVerticalGroup(
            botonAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(botonAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonAjustesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        barraSuperior.add(botonAjustes);

        jPanel1.add(barraSuperior, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(255, 0, 0));
        panelBotones.setMaximumSize(new java.awt.Dimension(200, 50));
        panelBotones.setMinimumSize(new java.awt.Dimension(200, 50));
        panelBotones.setName(""); // NOI18N
        panelBotones.setOpaque(false);
        panelBotones.setPreferredSize(new java.awt.Dimension(200, 50));
        panelBotones.setLayout(new javax.swing.BoxLayout(panelBotones, javax.swing.BoxLayout.LINE_AXIS));

        botonCambiar.setBackground(new java.awt.Color(255, 153, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("  Cerrar "); // NOI18N
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("  Sección"); // NOI18N
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonCambiarLayout = new javax.swing.GroupLayout(botonCambiar);
        botonCambiar.setLayout(botonCambiarLayout);
        botonCambiarLayout.setHorizontalGroup(
            botonCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(botonCambiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        botonCambiarLayout.setVerticalGroup(
            botonCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCambiarLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelBotones.add(botonCambiar);

        botonCerrar.setBackground(new java.awt.Color(255, 0, 0));
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("x");
        jLabel4.setToolTipText("");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonCerrarLayout = new javax.swing.GroupLayout(botonCerrar);
        botonCerrar.setLayout(botonCerrarLayout);
        botonCerrarLayout.setHorizontalGroup(
            botonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );
        botonCerrarLayout.setVerticalGroup(
            botonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
        );

        panelBotones.add(botonCerrar);

        jPanel1.add(panelBotones, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void botonAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAjustesMouseClicked
        ajustess = new ajustes(parametros, this);
        abrirVentana(ajustess);
    }//GEN-LAST:event_botonAjustesMouseClicked

    private void botonProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProveedoresMouseClicked
        proveedoresPanel proveedores = new proveedoresPanel(conexion);
        abrirVentana(proveedores);
    }//GEN-LAST:event_botonProveedoresMouseClicked

    private void botonVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseExited
        botonVentas.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botonVentasMouseExited

    private void botonVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseEntered
        botonVentas.setBackground(new Color(0,60,0));
    }//GEN-LAST:event_botonVentasMouseEntered

    private void botonVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseClicked
        ventasPanel = new ventasPanel(conexion, parametros);
        abrirVentana(ventasPanel);
    }//GEN-LAST:event_botonVentasMouseClicked

    private void botonProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseExited
        botonProductos.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_botonProductosMouseExited

    private void botonProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseEntered
        botonProductos.setBackground(new Color(0,60,0));
    }//GEN-LAST:event_botonProductosMouseEntered

    private void botonProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonProductosMouseClicked
        panelProductos = new productosPanel(conexion, parametros);
        abrirVentana(panelProductos);
    }//GEN-LAST:event_botonProductosMouseClicked

    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
        inicioPanel inicio = new inicioPanel();
        abrirVentana(inicio);
    }//GEN-LAST:event_botonInicioMouseClicked

    private void botonClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClientesMouseClicked
        clientesPanel clientes = new clientesPanel(conexion);
        abrirVentana(clientes);
    }//GEN-LAST:event_botonClientesMouseClicked

    private void botonClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonClientesMouseEntered

    private void botonClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClientesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonClientesMouseExited

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        try {
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(AlmacenJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(AlmacenJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void botonReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportesMouseClicked
        reportesPanel reportes = new reportesPanel(conexion, parametros);
        abrirVentana(reportes);
    }//GEN-LAST:event_botonReportesMouseClicked

    private void botonReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReportesMouseEntered

    private void botonReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReportesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReportesMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
        cargarLogin(conexion);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        dispose();
        cargarLogin(conexion);
    }//GEN-LAST:event_jLabel8MouseClicked
//carga y elimina los JPanel
    private void abrirVentana(JPanel panel){
        try{
       if (!panel.getName().equals(Paneles.getComponents()[0].getName())){
           Paneles.remove(ultimoPanel);
           Paneles.add(panel);
           ultimoPanel = panel;
           this.revalidate();
        }
        else{
            System.out.println("son iguales");
        }
        }
        catch(Exception e){
            System.out.println("Error en Panel");
        }
    }
//elimina los textos por defecto de los textBox cuando tiene el foco
    public void quitarTexto(Component componente){
        JTextField cajaTexto = (JTextField) componente;
        if (cajaTexto.getText().equals("0") || cajaTexto.getText().equals("0.0")){
            cajaTexto.setText(null);
        }
        
    }
    
//pone el texto predeterminado en los textbox vacios cuando pierden el foco
    public void ponerTexto(Component componente){
        JTextField cajaTexto = (JTextField) componente;
        if (cajaTexto.getText().equals("")){
            cajaTexto.setText("0");
        }
    }
    
    //solo permite ingresar numeros en los textBox
    private void soloNumeros(java.awt.event.KeyEvent evt){
        JTextField cajaTexto = (JTextField)evt.getComponent();
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean punto = key == 46;
        boolean borrar = key == 8;
        boolean enter = key == 10;
        if (!(numeros || punto || borrar))
        {
            evt.consume();
        }
        if (cajaTexto.getText().trim().length() == 20 && !(borrar)) {
            evt.consume();
        }
    }
    //solo permite 4 digitos numericos en los textBox
    private void porcentajeNumero(java.awt.event.KeyEvent evt){
        JTextField cajaTexto = (JTextField)evt.getComponent();
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean borrar = key == 8;
        if (!(numeros || borrar))
        {
            evt.consume();
        }
        if (cajaTexto.getText().trim().length() == 4 && !(borrar)) {
            evt.consume();
        }
    }
    
    private void pasarEnfoque(Component siguiente, java.awt.event.KeyEvent evt ){
        int key = evt.getKeyCode();
        boolean enter = key == 10;
        boolean flechaAbajo = key == 40;
        boolean flechaArriba = key == 38;
        
        if ((enter || flechaAbajo)){
            siguiente.transferFocus();
        }
        if (flechaArriba){
            siguiente.transferFocusBackward();
        }
    }
    
    private void insertarEnTabla(String producto, long codigo, int cantidad, int cantMin, float precio, String departamento){
    
        modelo.addRow(new Object[]{producto,codigo,cantidad, cantMin, precio, departamento});
    
    }
    
    private void cargarProductos(){
        ProductosBD productos;
        ResultSet set;
        productos = new ProductosBD(conexion);
        DepartamentoBD departamento = new DepartamentoBD(conexion);
        set = productos.obtenerProductos();
        limpiarTablas();
        
        try{
            while(set.next()){
                modeloProductos.addRow(new Object[]{set.getLong(1), set.getString(2),
                set.getInt(3), set.getInt(5), set.getFloat(4), departamento.getNombreDepartamento(set.getInt(6))});
            }
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }       
    }
    
    private void cargarProductosDepartamentos(int parametro){
        ProductosBD productos;
        ResultSet set;
        productos = new ProductosBD(conexion);
        DepartamentoBD departamento = new DepartamentoBD(conexion);
        set = productos.getProductosDepartamentos(parametro);
        limpiarTablas();
        
        try{
            while(set.next()){
                modeloProductos.addRow(new Object[]{set.getLong(1), set.getString(2),
                set.getInt(3), set.getInt(5), set.getFloat(4), departamento.getNombreDepartamento(set.getInt(6))});
            }
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    private void limpiarTablas(){
        int cantidad =modeloProductos.getRowCount()-1;  
        for(int i=cantidad;i>=0;i--){ 
            modeloProductos.removeRow(i);
        }
    }
    
    public void iniciarDia(boolean dia){
        if(dia){
            diaLabel.setText("Día iniciado");
        }
        else{
            diaLabel.setText("Día sin iniciar");
        } 
    }
    
    public void setDateDiaLabel(LocalDate fecha){
        this.fecha = fecha;
        fechaLabel.setText(fecha.format(formato));
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Paneles;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JPanel botonAjustes;
    private javax.swing.JPanel botonCambiar;
    private javax.swing.JPanel botonCerrar;
    private javax.swing.JPanel botonClientes;
    private javax.swing.JPanel botonInicio;
    private javax.swing.JPanel botonProductos;
    private javax.swing.JPanel botonProveedores;
    private javax.swing.JPanel botonReportes;
    private javax.swing.JPanel botonVentas;
    private javax.swing.JLabel diaLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelBotones;
    // End of variables declaration//GEN-END:variables
}
