/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import inventario.UsuariosBD;
import java.awt.Color;
import java.sql.Connection;
import static ventanas.AlmacenJframe.iniciarAlmacen;

/**
 *
 * @author angel
 */
public class LoginID extends javax.swing.JFrame {

    /**
     * Creates new form LoginID
     */
    int xMouse, yMouse;
    Connection conexion;
    UsuariosBD usuario;
    public LoginID(Connection con) {
        conexion = con;
        usuario = new UsuariosBD(con);
        initComponents();
    }
    
    public static void cargarLogin(Connection con){
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginID(con).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        botonCerrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioCampo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        claveCampo = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        iniciarBoton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BarraSuperior = new javax.swing.JPanel();
        ErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 400));

        botonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCerrarMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botonCerrarLayout = new javax.swing.GroupLayout(botonCerrar);
        botonCerrar.setLayout(botonCerrarLayout);
        botonCerrarLayout.setHorizontalGroup(
            botonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCerrarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        botonCerrarLayout.setVerticalGroup(
            botonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 60, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        usuarioCampo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuarioCampo.setForeground(new java.awt.Color(153, 153, 153));
        usuarioCampo.setText("Ingrese su usuario");
        usuarioCampo.setToolTipText("");
        usuarioCampo.setBorder(null);
        usuarioCampo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usuarioCampo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        usuarioCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioCampoMouseClicked(evt);
            }
        });
        usuarioCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioCampoKeyPressed(evt);
            }
        });
        getContentPane().add(usuarioCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 270, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 270, 10));

        claveCampo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        claveCampo.setForeground(new java.awt.Color(153, 153, 153));
        claveCampo.setText("***************");
        claveCampo.setBorder(null);
        claveCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                claveCampoMousePressed(evt);
            }
        });
        getContentPane().add(claveCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 270, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("INICIO DE SECCIÓN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 270, 10));

        iniciarBoton.setBackground(new java.awt.Color(0, 102, 0));
        iniciarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarBotonMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Iniciar");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout iniciarBotonLayout = new javax.swing.GroupLayout(iniciarBoton);
        iniciarBoton.setLayout(iniciarBotonLayout);
        iniciarBotonLayout.setHorizontalGroup(
            iniciarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciarBotonLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        iniciarBotonLayout.setVerticalGroup(
            iniciarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iniciarBotonLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(iniciarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 110, 50));

        BarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraSuperiorMouseDragged(evt);
            }
        });
        BarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraSuperiorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(BarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 50));

        ErrorLabel.setForeground(new java.awt.Color(255, 0, 51));
        ErrorLabel.setText(" ");
        getContentPane().add(ErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void BarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_BarraSuperiorMousePressed

    private void BarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraSuperiorMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       
       this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_BarraSuperiorMouseDragged

    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseEntered
        botonCerrar.setBackground(Color.red);
    }//GEN-LAST:event_botonCerrarMouseEntered

    private void botonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseExited
        botonCerrar.setBackground(Color.white);
    }//GEN-LAST:event_botonCerrarMouseExited

    private void usuarioCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioCampoMouseClicked
        if (usuarioCampo.getText().equals("Ingrese su usuario")){
            usuarioCampo.setText("");
            usuarioCampo.setForeground(Color.black);
        }
        if(String.valueOf(claveCampo.getPassword()).equals( "")){
            claveCampo.setText("***************");
            claveCampo.setForeground(Color.gray);
        }        
        
    }//GEN-LAST:event_usuarioCampoMouseClicked

    private void claveCampoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claveCampoMousePressed
        if (String.valueOf(claveCampo.getPassword()).equals( "***************")){
            claveCampo.setText("");
            claveCampo.setForeground(Color.black);
        }
        if(usuarioCampo.getText().equals("")){
            usuarioCampo.setForeground(Color.gray);
            usuarioCampo.setText("Ingrese su usuario");

        }
    }//GEN-LAST:event_claveCampoMousePressed

    private void usuarioCampoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioCampoKeyPressed
        if (usuarioCampo.getText().equals("Ingrese su usuario")){
            usuarioCampo.setText("");
            usuarioCampo.setForeground(Color.black);
        }

        
    }//GEN-LAST:event_usuarioCampoKeyPressed

    private void iniciarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarBotonMouseClicked
        try{
            if(usuario.accederUsuario(usuarioCampo.getText(), claveCampo.getText())){
                String nombre = usuarioCampo.getText();
                iniciarAlmacen(conexion, nombre);
                dispose();
                
            }
            else{
                ErrorLabel.setText("Error al iniciar seccion");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_iniciarBotonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JPanel botonCerrar;
    private javax.swing.JPasswordField claveCampo;
    private javax.swing.JPanel iniciarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField usuarioCampo;
    // End of variables declaration//GEN-END:variables
}
