/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import static VentanasEmergentes.InformacionProveedor.crearVentanaInformacionProveedor;
import inventario.ObtenerParametros;
import inventario.Proveedorees;
import inventario.ProveedoresBD;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class proveedoresPanel extends javax.swing.JPanel {

    /**
     * Creates new form ajustes
     */
    Connection conexion;
    ObtenerParametros parametros;
    ProveedoresBD proveedorBD;
    DefaultTableModel modeloAgregar;
    boolean actualizado = false;
    
    public proveedoresPanel(Connection con) {
        datos();
        initComponents();
        conexion = con;
        modeloAgregar = (DefaultTableModel) tablaProveedores.getModel();
        proveedorBD = new ProveedoresBD(conexion);    
        cargarProveedores();
    }

    /**
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregarBoton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rifTexto = new javax.swing.JTextField();
        nombreTexto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        direccionTexto = new javax.swing.JTextField();
        telefonoTexto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelScrol = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        buscadorTexto = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonBuscar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("proveedores"); // NOI18N
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Datos del proveedor:");

        agregarBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agregarBoton.setText("Agregar Proveedor");
        agregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBotonActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6.setText("Cancelar");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("RIF:");

        rifTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rifTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rifTextoActionPerformed(evt);
            }
        });

        nombreTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Dirección:");

        direccionTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        direccionTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTextoActionPerformed(evt);
            }
        });

        telefonoTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        telefonoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTextoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Teléfono");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Proveedores");

        panelScrol.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelScrol.setFocusCycleRoot(true);
        panelScrol.setFont(new java.awt.Font("Yu Gothic UI", 0, 48)); // NOI18N

        tablaProveedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RIF", "Nombre", "Dirección", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProveedores.setRowHeight(40);
        tablaProveedores.setShowHorizontalLines(true);
        tablaProveedores.setShowVerticalLines(true);
        tablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveedoresMouseClicked(evt);
            }
        });
        panelScrol.setViewportView(tablaProveedores);

        buscadorTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscadorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorTextoActionPerformed(evt);
            }
        });
        buscadorTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscadorTextoKeyPressed(evt);
            }
        });

        botonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonBuscar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonBuscar1.setText("Todos");
        botonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelScrol, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(buscadorTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(175, 175, 175))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar)
                    .addComponent(botonBuscar1))
                .addGap(7, 7, 7)
                .addComponent(panelScrol, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 52, Short.MAX_VALUE)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(agregarBoton))
                            .addComponent(telefonoTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(direccionTexto)
                            .addComponent(nombreTexto)
                            .addComponent(rifTexto)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(0, 280, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rifTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarBoton)
                            .addComponent(jButton6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    private void datos(){
   
    }
    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
       
    }//GEN-LAST:event_formAncestorAdded

    private void rifTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rifTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rifTextoActionPerformed

    private void nombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextoActionPerformed

    private void telefonoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTextoActionPerformed

    private void direccionTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTextoActionPerformed

    private void tablaProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedoresMouseClicked

        if (evt.getClickCount() == 2){
            String rif = (String)tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 0);
            if(crearVentanaInformacionProveedor(conexion,rif)){
                cargarProveedores();
            }
        }
    }//GEN-LAST:event_tablaProveedoresMouseClicked

    private void buscadorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscadorTextoActionPerformed

    private void agregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBotonActionPerformed
        System.out.println(rifTexto.getText()+nombreTexto.getText());
        if(!(rifTexto.getText().isEmpty() || nombreTexto.getText().isEmpty())){
            proveedorBD.SetProveedor(rifTexto.getText(), nombreTexto.getText(), direccionTexto.getText(), telefonoTexto.getText());
            modeloAgregar.addRow(new Object[]{rifTexto.getText(), nombreTexto.getText(),
            direccionTexto.getText(), telefonoTexto.getText()});
            rifTexto.setText("");
            nombreTexto.setText("");
            direccionTexto.setText("");
            telefonoTexto.setText("");
            JOptionPane.showMessageDialog(null, "Proveedor agregardo con éxito");
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese los datos");
        }
    }//GEN-LAST:event_agregarBotonActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        Proveedorees proveedor = proveedorBD.buscadorProveedor(buscadorTexto.getText());
        System.out.println(proveedor.getNombre());
        if(!(proveedor.getNombre() == null)){
            limpiarTablas();
             modeloAgregar.addRow(new Object[]{proveedor.getRif(), proveedor.getNombre(),
                    proveedor.getDireccion(), proveedor.getTelefono()});
            }
        else{
            JOptionPane.showMessageDialog(null, "Proveedor no encontrado");
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void buscadorTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorTextoKeyPressed
        Proveedorees proveedor = proveedorBD.buscadorProveedor(buscadorTexto.getText());
        int key = evt.getKeyCode();
        boolean enter = key == 10;
        if ((enter)){
            if(!(proveedor.getNombre() == null)){
                limpiarTablas();
                modeloAgregar.addRow(new Object[]{proveedor.getRif(), proveedor.getNombre(),
                proveedor.getDireccion(), proveedor.getTelefono()});
            }
            else{
                JOptionPane.showMessageDialog(null, "Proveedor no encontrado");
            }

        }
    }//GEN-LAST:event_buscadorTextoKeyPressed

    private void botonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscar1ActionPerformed
       cargarProveedores();
    }//GEN-LAST:event_botonBuscar1ActionPerformed
    
    private void cargarProveedores(){
        ProveedoresBD proveedores;
        ResultSet set;
        proveedores = new ProveedoresBD(conexion);
        set = proveedores.cargarProveedores();
        float precio;
        limpiarTablas();
        try{
            while(set.next()){
                modeloAgregar.addRow(new Object[]{set.getString(1), set.getString(2),
                set.getString(3), set.getString(4)});
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void limpiarTablas(){
        int cantidad =modeloAgregar.getRowCount()-1;  
        for(int i=cantidad;i>=0;i--){ 
            modeloAgregar.removeRow(i);
        }
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBoton;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonBuscar1;
    private javax.swing.JTextField buscadorTexto;
    private javax.swing.JTextField direccionTexto;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JScrollPane panelScrol;
    private javax.swing.JTextField rifTexto;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField telefonoTexto;
    // End of variables declaration//GEN-END:variables
}
