/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import static Reportes.Ticket.imprimir;
import inventario.ClienteBD;
import inventario.ObtenerParametros;
import inventario.VentasBD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class reportesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ajustes
     */
    Connection conexion;
    ObtenerParametros parametros;
    ClienteBD clienteBD;
    DefaultTableModel modeloAgregar;
    boolean actualizado = false;
    
    public reportesPanel(Connection con, ObtenerParametros parametros) {
        datos();
        initComponents();
        conexion = con;
        this.parametros = parametros;
        modeloAgregar = (DefaultTableModel) tablaClientes.getModel();
        clienteBD = new ClienteBD(conexion);    
        cargarClientes();
    }

    /**
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelScrol = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("reportes"); // NOI18N
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new java.awt.BorderLayout());

        panelScrol.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelScrol.setFocusCycleRoot(true);
        panelScrol.setFont(new java.awt.Font("Yu Gothic UI", 0, 48)); // NOI18N

        tablaClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Factura", "Fecha", "Cleinte", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.setRowHeight(40);
        tablaClientes.setShowHorizontalLines(true);
        tablaClientes.setShowVerticalLines(true);
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        panelScrol.setViewportView(tablaClientes);

        jScrollPane1.setViewportView(panelScrol);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    private void datos(){
   
    }
    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
       
    }//GEN-LAST:event_formAncestorAdded

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked

        if (evt.getClickCount() == 2){
            int numeroFactura =Integer.parseInt((String) tablaClientes.getValueAt(tablaClientes.getSelectedRow(), 0));
            try{
                imprimir(numeroFactura, parametros, conexion);
            }
            catch(Exception e){
            
            }
//                    File pdfFile = new File("src/pdf/venta.pdf");
//        
//        if (Desktop.isDesktopSupported()) {
//            Desktop desktop = Desktop.getDesktop();
//            
//            if (pdfFile.exists()) {
//                try {
//                    desktop.open(pdfFile);
//                } catch (IOException e) {
//                    System.out.println("Error desde reportes panel " + e.getMessage());
//                }
//            } else {
//                System.out.println("Error desde reportes panel " +"El archivo no existe");
//            }
//            } else {
//                System.out.println("Error desde reportes panel " +"Desktop no está soportado");
//            }
        }
        
    }//GEN-LAST:event_tablaClientesMouseClicked
    
    private void cargarClientes(){
        VentasBD ventaBD = new VentasBD(conexion);
        ResultSet set;
        set = ventaBD.getVentas();
        float precio;
        limpiarTablas();
        try{
            while(set.next()){
                modeloAgregar.addRow(new Object[]{set.getString(1), set.getString(2),
                set.getString(3), set.getString(4)});
            }
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    private void limpiarTablas(){
        int cantidad =modeloAgregar.getRowCount()-1;  
        for(int i=cantidad;i>=0;i--){ 
            modeloAgregar.removeRow(i);
        }
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane panelScrol;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
