/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import inventario.ObtenerParametros;
import java.io.IOException;

/**
 *
 * @author angel
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form ajustes
     */
    ObtenerParametros parametros;
    String nombre, direccion, rif;
    int iva, ganancia; 
    double tasa;
    public Usuarios(ObtenerParametros parametros) {
        this.parametros = parametros;
        datos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
    ObtenerParametros parametros;
    String nombre, direccion, rif;
    int tasa, iva, ganancia; 
    public ajustes(ObtenerParametros parametros) {
        parametros = this.parametros;
        datos();
        initComponents();
    }

    /**
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        ventasRadio = new javax.swing.JRadioButton();
        productosRadio = new javax.swing.JRadioButton();
        proveedoresRadio = new javax.swing.JRadioButton();
        usuariosRadio = new javax.swing.JRadioButton();
        ReportesRadio = new javax.swing.JRadioButton();
        ajustesRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JTextField();
        contrasenaTexto = new javax.swing.JTextField();
        repetirContrasenaTexto = new javax.swing.JTextField();
        agregarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();
        proveedoresRadio1 = new javax.swing.JRadioButton();
        ReportesRadio1 = new javax.swing.JRadioButton();
        usuariosRadio1 = new javax.swing.JRadioButton();
        usuariosRadio2 = new javax.swing.JRadioButton();
        usuariosRadio3 = new javax.swing.JRadioButton();
        agregarBoton1 = new javax.swing.JButton();
        nombreTexto1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tablaUsuarios1 = new javax.swing.JScrollPane();
        TablaProductos1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tablaUsuarios = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        agregarBoton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setName("usuarios"); // NOI18N
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new java.awt.BorderLayout());

        ventasRadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ventasRadio.setText("Ventas");

        productosRadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productosRadio.setText("Productos");

        proveedoresRadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        proveedoresRadio.setText("Proveedores");

        usuariosRadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuariosRadio.setText("Usuarios");

        ReportesRadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ReportesRadio.setText("Reportes");

        ajustesRadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ajustesRadio.setText("Ajustes");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Agregar estatus");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Establesca el nombre de usuario y la contraseña");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña");

        nombreTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreTexto.setForeground(new java.awt.Color(153, 153, 153));
        nombreTexto.setText("Ingrese el nombre de usuario");
        nombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextoActionPerformed(evt);
            }
        });

        contrasenaTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contrasenaTexto.setForeground(new java.awt.Color(153, 153, 153));
        contrasenaTexto.setText("Ingrese la contraseña");

        repetirContrasenaTexto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        repetirContrasenaTexto.setForeground(new java.awt.Color(153, 153, 153));
        repetirContrasenaTexto.setText("Repita la contraseña");

        agregarBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agregarBoton.setText("Agregar Usuario");

        CancelarBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CancelarBoton.setText("Cancelar");

        proveedoresRadio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        proveedoresRadio1.setText("Clientes");
        proveedoresRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresRadio1ActionPerformed(evt);
            }
        });

        ReportesRadio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ReportesRadio1.setText("Departamentos");
        ReportesRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesRadio1ActionPerformed(evt);
            }
        });

        usuariosRadio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuariosRadio1.setText("Permiso de modificar");

        usuariosRadio2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuariosRadio2.setText("Permisos de Administrador");
        usuariosRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosRadio2ActionPerformed(evt);
            }
        });

        usuariosRadio3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuariosRadio3.setText("Permiso de agregar");

        agregarBoton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agregarBoton1.setText("Agregar Estatus");
        agregarBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBoton1ActionPerformed(evt);
            }
        });

        nombreTexto1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreTexto1.setForeground(new java.awt.Color(153, 153, 153));
        nombreTexto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTexto1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Estatus");

        jPanel3.setPreferredSize(new java.awt.Dimension(250, 610));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Estatus Registrados");

        tablaUsuarios1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaUsuarios1.setFocusCycleRoot(true);
        tablaUsuarios1.setFont(new java.awt.Font("Yu Gothic UI", 0, 48)); // NOI18N

        TablaProductos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TablaProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaProductos1.setRowHeight(40);
        TablaProductos1.setShowHorizontalLines(true);
        TablaProductos1.setShowVerticalLines(true);
        TablaProductos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductos1MouseClicked(evt);
            }
        });
        tablaUsuarios1.setViewportView(TablaProductos1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaUsuarios1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaUsuarios1)
                .addContainerGap())
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 480));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Usuarios Registrados");

        tablaUsuarios.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaUsuarios.setFocusCycleRoot(true);
        tablaUsuarios.setFont(new java.awt.Font("Yu Gothic UI", 0, 48)); // NOI18N

        TablaProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Estatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos.setRowHeight(40);
        TablaProductos.setShowHorizontalLines(true);
        TablaProductos.setShowVerticalLines(true);
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        tablaUsuarios.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setHeaderValue("Usuario");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaUsuarios)
                .addContainerGap())
        );

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Estatus");

        agregarBoton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agregarBoton2.setText("Nuevo Estatus");
        agregarBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBoton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuariosRadio)
                            .addComponent(ReportesRadio)
                            .addComponent(ajustesRadio)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(proveedoresRadio)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(productosRadio)
                                            .addComponent(ventasRadio)
                                            .addComponent(proveedoresRadio1))
                                        .addGap(184, 184, 184)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usuariosRadio3)
                                            .addComponent(usuariosRadio1)
                                            .addComponent(usuariosRadio2)))
                                    .addComponent(ReportesRadio1)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8)))
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreTexto1)
                            .addComponent(contrasenaTexto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTexto)
                            .addComponent(repetirContrasenaTexto)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(CancelarBoton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(agregarBoton))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(agregarBoton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(agregarBoton1)))))
                        .addGap(21, 21, 21))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productosRadio)
                            .addComponent(usuariosRadio2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ventasRadio)
                            .addComponent(usuariosRadio1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proveedoresRadio1)
                            .addComponent(usuariosRadio3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proveedoresRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReportesRadio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReportesRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuariosRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajustesRadio)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarBoton1)
                            .addComponent(agregarBoton2))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contrasenaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(repetirContrasenaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CancelarBoton)
                            .addComponent(agregarBoton))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    private void datos(){
        nombre = parametros.getNombre();
        direccion = parametros.getDireccion();
        rif = parametros.getRif();
        tasa = parametros.getTasa();
        iva = parametros.getIva();
        ganancia = parametros.getGanancia();
    }
    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
       
    }//GEN-LAST:event_formAncestorAdded

    private void nombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextoActionPerformed

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked

    }//GEN-LAST:event_TablaProductosMouseClicked

    private void proveedoresRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresRadio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedoresRadio1ActionPerformed

    private void usuariosRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosRadio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariosRadio2ActionPerformed

    private void ReportesRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesRadio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportesRadio1ActionPerformed

    private void agregarBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBoton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarBoton1ActionPerformed

    private void nombreTexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTexto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTexto1ActionPerformed

    private void TablaProductos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaProductos1MouseClicked

    private void agregarBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBoton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarBoton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JRadioButton ReportesRadio;
    private javax.swing.JRadioButton ReportesRadio1;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTable TablaProductos1;
    private javax.swing.JButton agregarBoton;
    private javax.swing.JButton agregarBoton1;
    private javax.swing.JButton agregarBoton2;
    private javax.swing.JRadioButton ajustesRadio;
    private javax.swing.JTextField contrasenaTexto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JTextField nombreTexto1;
    private javax.swing.JRadioButton productosRadio;
    private javax.swing.JRadioButton proveedoresRadio;
    private javax.swing.JRadioButton proveedoresRadio1;
    private javax.swing.JTextField repetirContrasenaTexto;
    private javax.swing.JScrollPane tablaUsuarios;
    private javax.swing.JScrollPane tablaUsuarios1;
    private javax.swing.JRadioButton usuariosRadio;
    private javax.swing.JRadioButton usuariosRadio1;
    private javax.swing.JRadioButton usuariosRadio2;
    private javax.swing.JRadioButton usuariosRadio3;
    private javax.swing.JRadioButton ventasRadio;
    // End of variables declaration//GEN-END:variables
}
