/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasEmergentes;

import inventario.ClientesBD;
import inventario.DepartamentoBD;
import inventario.ObtenerParametros;
import inventario.Productos;
import java.awt.Component;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class agregarCliente extends javax.swing.JFrame {
    Connection conexion;
    String idCliente;
    DepartamentoBD departamento;
    Productos producto;
    ObtenerParametros parametros;
    /**
     * Creates new form InformacionProducto
     * @param con
     * @param codigo
     * @throws java.sql.SQLException
     */
    public agregarCliente(Connection con,String idCliente) throws SQLException {
        conexion = con;
        this.parametros = parametros;
        this.idCliente = idCliente;
        departamento= new DepartamentoBD(con);
        initComponents();
        idClienteTexto.setText(idCliente);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        idClienteTexto = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        direccionTexto = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        telefonoTexto = new javax.swing.JTextField();
        guardarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar nuevo cliente");
        jPanel1.add(jLabel1);

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel26.setText("ID Cliente");

        idClienteTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        idClienteTexto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        idClienteTexto.setName("nombreTexto"); // NOI18N
        idClienteTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idClienteTextoKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel27.setText("Nombre:");

        nombreTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        nombreTexto.setName("nombreTexto"); // NOI18N
        nombreTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTextoFocusLost(evt);
            }
        });
        nombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextoActionPerformed(evt);
            }
        });
        nombreTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreTextoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTextoKeyTyped(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel28.setText("Dirección:");

        direccionTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        direccionTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                direccionTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                direccionTextoFocusLost(evt);
            }
        });
        direccionTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTextoActionPerformed(evt);
            }
        });
        direccionTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                direccionTextoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccionTextoKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel29.setText("Teléfono");

        telefonoTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        telefonoTexto.setName("precioTexto"); // NOI18N
        telefonoTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoTextoFocusLost(evt);
            }
        });
        telefonoTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoTextoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTextoKeyTyped(evt);
            }
        });

        guardarBoton.setText("Registrar");
        guardarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarBotonMouseClicked(evt);
            }
        });
        guardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idClienteTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(nombreTexto)
                    .addComponent(direccionTexto)
                    .addComponent(telefonoTexto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarBoton)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idClienteTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idClienteTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idClienteTextoKeyPressed
        pasarEnfoque(idClienteTexto, evt);
    }//GEN-LAST:event_idClienteTextoKeyPressed

    private void nombreTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTextoFocusGained

    }//GEN-LAST:event_nombreTextoFocusGained

    private void nombreTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreTextoFocusLost

    }//GEN-LAST:event_nombreTextoFocusLost

    private void nombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextoActionPerformed

    private void nombreTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTextoKeyPressed
        pasarEnfoque(nombreTexto, evt);
    }//GEN-LAST:event_nombreTextoKeyPressed

    private void nombreTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTextoKeyTyped

    }//GEN-LAST:event_nombreTextoKeyTyped

    private void direccionTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTextoFocusGained

    }//GEN-LAST:event_direccionTextoFocusGained

    private void direccionTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_direccionTextoFocusLost

    }//GEN-LAST:event_direccionTextoFocusLost

    private void direccionTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTextoActionPerformed

    private void direccionTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTextoKeyPressed
        pasarEnfoque(direccionTexto, evt);
    }//GEN-LAST:event_direccionTextoKeyPressed

    private void direccionTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTextoKeyTyped

    }//GEN-LAST:event_direccionTextoKeyTyped

    private void telefonoTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTextoFocusGained

    }//GEN-LAST:event_telefonoTextoFocusGained

    private void telefonoTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoTextoFocusLost

    }//GEN-LAST:event_telefonoTextoFocusLost

    private void telefonoTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTextoKeyPressed
        pasarEnfoque(telefonoTexto, evt);
    }//GEN-LAST:event_telefonoTextoKeyPressed

    private void telefonoTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTextoKeyTyped

    }//GEN-LAST:event_telefonoTextoKeyTyped

    private void guardarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBotonMouseClicked

    }//GEN-LAST:event_guardarBotonMouseClicked

    private void guardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotonActionPerformed
        if(idClienteTexto.getText() != null && nombreTexto.getText() != null && direccionTexto.getText() != null && telefonoTexto.getText() != null){
             ClientesBD clienteBD = new ClientesBD(conexion);
             clienteBD.SetCliente(idClienteTexto.getText(), nombreTexto.getText(), direccionTexto.getText(), telefonoTexto.getText());
             dispose();
             JOptionPane.showMessageDialog(null, "Cliente agregado con éxito");
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
        }
        
    }//GEN-LAST:event_guardarBotonActionPerformed

    /**
     * @param con
     * @param idCliente
     */
    public static void crearVentanaCliente(Connection con, String idCliente) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new agregarCliente(con, idCliente).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(agregarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    private void pasarEnfoque(Component siguiente, java.awt.event.KeyEvent evt ){
        int key = evt.getKeyCode();
        boolean enter = key == 10;
        boolean flechaAbajo = key == 40;
        boolean flechaArriba = key == 38;
        
        if ((enter || flechaAbajo)){
            siguiente.transferFocus();
        }
        if (flechaArriba){
            siguiente.transferFocusBackward();
        }
    }

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField direccionTexto;
    private javax.swing.JButton guardarBoton;
    private javax.swing.JTextField idClienteTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JTextField telefonoTexto;
    // End of variables declaration//GEN-END:variables
}
