/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasEmergentes;

import inventario.Clientes;
import inventario.ClienteBD;
import inventario.ProveedoresBD;
import java.awt.Component;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author angel
 */
public class InformacionCliente extends javax.swing.JFrame {
    Connection conexion;
    Clientes clientes;
    String identificador;
    static boolean ok = false;
    /**
     * Creates new form InformacionProducto
     * @param con
     * @param identificador
     * @throws java.sql.SQLException
     */
    public InformacionCliente(Connection con,String identificador) throws SQLException {
        conexion = con;
        System.out.println(identificador);
        this.identificador = identificador;
        clientes = new Clientes();
        initComponents();
        cargarCliente(identificador);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        identificadorTexto = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        direccionTexto = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        telefonoTexto = new javax.swing.JTextField();
        editarBoton = new javax.swing.JButton();
        guardarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(540, 429));

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Información del cliente");
        jPanel1.add(jLabel1);

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel26.setText("Identificador:");

        identificadorTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        identificadorTexto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        identificadorTexto.setEnabled(false);
        identificadorTexto.setName("nombreTexto"); // NOI18N
        identificadorTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                identificadorTextoKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel27.setText("Nombre:");

        nombreTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        nombreTexto.setEnabled(false);
        nombreTexto.setName("nombreTexto"); // NOI18N
        nombreTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreTextoKeyPressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel28.setText("Dirección:");

        direccionTexto.setEditable(false);
        direccionTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        direccionTexto.setEnabled(false);
        direccionTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                direccionTextoKeyPressed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel29.setText("Teléfono:");

        telefonoTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        telefonoTexto.setEnabled(false);
        telefonoTexto.setName("precioTexto"); // NOI18N
        telefonoTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefonoTextoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoTextoKeyTyped(evt);
            }
        });

        editarBoton.setText("Editar");
        editarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarBotonMouseClicked(evt);
            }
        });
        editarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBotonActionPerformed(evt);
            }
        });

        guardarBoton.setText("Guardar");
        guardarBoton.setEnabled(false);
        guardarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarBotonMouseClicked(evt);
            }
        });
        guardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotonActionPerformed(evt);
            }
        });

        eliminarBoton.setText("Eliminar");
        eliminarBoton.setEnabled(false);
        eliminarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarBotonMouseClicked(evt);
            }
        });
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificadorTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(nombreTexto)
                    .addComponent(direccionTexto)
                    .addComponent(telefonoTexto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(eliminarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarBoton))
                    .addComponent(editarBoton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identificadorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void identificadorTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identificadorTextoKeyPressed
        pasarEnfoque(identificadorTexto, evt);
    }//GEN-LAST:event_identificadorTextoKeyPressed

    private void nombreTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTextoKeyPressed
        pasarEnfoque(nombreTexto, evt);
    }//GEN-LAST:event_nombreTextoKeyPressed

    private void direccionTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccionTextoKeyPressed
        pasarEnfoque(direccionTexto, evt);
    }//GEN-LAST:event_direccionTextoKeyPressed

    private void telefonoTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTextoKeyPressed
        pasarEnfoque(telefonoTexto, evt);
    }//GEN-LAST:event_telefonoTextoKeyPressed

    private void telefonoTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoTextoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_telefonoTextoKeyTyped

    private void editarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBotonActionPerformed
        
    }//GEN-LAST:event_editarBotonActionPerformed

    private void editarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBotonMouseClicked
        nombreTexto.setEnabled(true);
        telefonoTexto.setEnabled(true);
        direccionTexto.setEnabled(true);
        guardarBoton.setEnabled(true);
        eliminarBoton.setEnabled(true);
        editarBoton.setVisible(false);
    }//GEN-LAST:event_editarBotonMouseClicked

    private void guardarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBotonMouseClicked
        ClienteBD clienteBD = new ClienteBD(conexion);
        clientes.setNombre(nombreTexto.getText());
        clientes.setDireccion(direccionTexto.getText());
        clientes.setTelefono(telefonoTexto.getText());
        clientes.setIdentificador(identificadorTexto.getText());
        clienteBD.actualizarCliente(clientes);
        ok = true;
        dispose();
    }//GEN-LAST:event_guardarBotonMouseClicked

    private void guardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarBotonActionPerformed

    private void eliminarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBotonMouseClicked

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        ClienteBD clienteBD = new ClienteBD(conexion);
        clienteBD.eliminarCliente(identificador);
        dispose();
    }//GEN-LAST:event_eliminarBotonActionPerformed

    /**
     * @param con
     * @param identificador
     */
    public static boolean crearVentanaInformacionCliente(Connection con, String identificador) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new InformacionCliente(con, identificador).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(InformacionCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        return ok;     
    }
    public void cargarCliente(String identificador) throws SQLException{
        ClienteBD clientesBD = new ClienteBD(conexion);
        clientes = clientesBD.getCliente(identificador);
        identificadorTexto.setText(identificador);
        nombreTexto.setText(clientes.getNombre());
        direccionTexto.setText(clientes.getDireccion());
        telefonoTexto.setText(clientes.getTelefono());    
    }
    
    

    public void quitarTexto(Component componente){
        JTextField cajaTexto = (JTextField) componente;
        if (cajaTexto.getText().equals("0") || cajaTexto.getText().equals("0.0")){
            cajaTexto.setText(null);
        }
        
    }
    
    private void pasarEnfoque(Component siguiente, java.awt.event.KeyEvent evt ){
        int key = evt.getKeyCode();
        boolean enter = key == 10;
        boolean flechaAbajo = key == 40;
        boolean flechaArriba = key == 38;
        
        if ((enter || flechaAbajo)){
            siguiente.transferFocus();
        }
        if (flechaArriba){
            siguiente.transferFocusBackward();
        }
    }
            //pone el texto predeterminado en los textbox vacios cuando pierden el foco
    public void ponerTexto(Component componente){
        JTextField cajaTexto = (JTextField) componente;
        if (cajaTexto.getText().equals("")){
            cajaTexto.setText("0");
        }
    }
    
    //solo permite ingresar numeros en los textBox
    private void soloNumeros(java.awt.event.KeyEvent evt){
        JTextField cajaTexto = (JTextField)evt.getComponent();
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean punto = key == 46;
        boolean borrar = key == 8;
        boolean enter = key == 10;
        if (!(numeros || punto || borrar))
        {
            evt.consume();
        }
        if (cajaTexto.getText().trim().length() == 20 && !(borrar)) {
            evt.consume();
        }
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField direccionTexto;
    private javax.swing.JButton editarBoton;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JButton guardarBoton;
    private javax.swing.JTextField identificadorTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JTextField telefonoTexto;
    // End of variables declaration//GEN-END:variables
}
