/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentanasEmergentes;

import inventario.DepartamentoBD;
import inventario.ObtenerParametros;
import inventario.Productos;
import inventario.ProductosBD;
import inventario.ProveedoresBD;
import java.awt.Component;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author angel
 */
public class InformacionProducto extends javax.swing.JFrame {
    Connection conexion;
    String codigo;
    DepartamentoBD departamento;
    ProveedoresBD proveedores;
    Productos producto;
    ObtenerParametros parametros;
    boolean gananciaUltimo;
    boolean ivaUltimo;
    double precioFinalUltimo;
    /**
     * Creates new form InformacionProducto
     * @param con
     * @param codigo
     * @throws java.sql.SQLException
     */
    public InformacionProducto(Connection con,String codigo, ObtenerParametros parametros) throws SQLException {
        conexion = con;
        this.parametros = parametros;
        this.codigo = codigo;
        departamento= new DepartamentoBD(con);
        proveedores = new ProveedoresBD(conexion);
        initComponents();
        cargarProducto();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        productoTexto = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        codigoTexto = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cantidadTexto = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cantidadMinTexto = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        precioTexto = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        precioBolivarTexto = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        comboDepartamentos = new javax.swing.JComboBox<>();
        editarBoton = new javax.swing.JButton();
        guardarBoton = new javax.swing.JButton();
        gananciaPorcentajeTexto = new javax.swing.JTextField();
        ivaPorcentajeTexto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        precioCostoTexto = new javax.swing.JTextField();
        gananciaTexto = new javax.swing.JTextField();
        ivaTexto = new javax.swing.JTextField();
        eliminarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(533, 879));
        setMinimumSize(new java.awt.Dimension(533, 879));

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Información del prodcuto");
        jPanel1.add(jLabel1);

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel26.setText("Producto:");

        productoTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        productoTexto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        productoTexto.setEnabled(false);
        productoTexto.setName("nombreTexto"); // NOI18N
        productoTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productoTextoKeyPressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel27.setText("Código:");

        codigoTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        codigoTexto.setText("0");
        codigoTexto.setEnabled(false);
        codigoTexto.setName("nombreTexto"); // NOI18N
        codigoTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoTextoFocusLost(evt);
            }
        });
        codigoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextoActionPerformed(evt);
            }
        });
        codigoTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoTextoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoTextoKeyTyped(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel28.setText("Cantidad:");

        cantidadTexto.setEditable(false);
        cantidadTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        cantidadTexto.setText("0");
        cantidadTexto.setEnabled(false);
        cantidadTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidadTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidadTextoFocusLost(evt);
            }
        });
        cantidadTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTextoActionPerformed(evt);
            }
        });
        cantidadTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadTextoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadTextoKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel29.setText("Cantidad mín:");

        cantidadMinTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        cantidadMinTexto.setText("0");
        cantidadMinTexto.setEnabled(false);
        cantidadMinTexto.setName("precioTexto"); // NOI18N
        cantidadMinTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidadMinTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidadMinTextoFocusLost(evt);
            }
        });
        cantidadMinTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadMinTextoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadMinTextoKeyTyped(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel30.setText("Precio costo:");

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel31.setText("Ganancia:");

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel32.setText("IVA:");

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel33.setText("Precio:");

        precioTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        precioTexto.setText("0");
        precioTexto.setEnabled(false);
        precioTexto.setName("precioTexto"); // NOI18N
        precioTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioTextoFocusLost(evt);
            }
        });
        precioTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioTextoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioTextoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioTextoKeyTyped(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel34.setText("Precio en Bs:");

        precioBolivarTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        precioBolivarTexto.setText("0");
        precioBolivarTexto.setEnabled(false);
        precioBolivarTexto.setName("precioBolivaresTexto"); // NOI18N
        precioBolivarTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioBolivarTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioBolivarTextoFocusLost(evt);
            }
        });
        precioBolivarTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precioBolivarTextoMouseClicked(evt);
            }
        });
        precioBolivarTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioBolivarTextoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioBolivarTextoKeyTyped(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel35.setText("Departamento:");

        comboDepartamentos.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        comboDepartamentos.setEnabled(false);

        editarBoton.setText("Editar");
        editarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarBotonMouseClicked(evt);
            }
        });
        editarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBotonActionPerformed(evt);
            }
        });

        guardarBoton.setText("Guardar");
        guardarBoton.setEnabled(false);
        guardarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarBotonMouseClicked(evt);
            }
        });
        guardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotonActionPerformed(evt);
            }
        });

        gananciaPorcentajeTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        gananciaPorcentajeTexto.setEnabled(false);
        gananciaPorcentajeTexto.setName("precioTexto"); // NOI18N
        gananciaPorcentajeTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gananciaPorcentajeTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gananciaPorcentajeTextoFocusLost(evt);
            }
        });
        gananciaPorcentajeTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gananciaPorcentajeTextoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gananciaPorcentajeTextoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gananciaPorcentajeTextoKeyTyped(evt);
            }
        });

        ivaPorcentajeTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        ivaPorcentajeTexto.setEnabled(false);
        ivaPorcentajeTexto.setName("ivaPorcentajeTexto"); // NOI18N
        ivaPorcentajeTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ivaPorcentajeTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ivaPorcentajeTextoFocusLost(evt);
            }
        });
        ivaPorcentajeTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ivaPorcentajeTextoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ivaPorcentajeTextoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ivaPorcentajeTextoKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel13.setText("%");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel11.setText("%");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel12.setText("$");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel14.setText("$");

        precioCostoTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        precioCostoTexto.setText("0");
        precioCostoTexto.setEnabled(false);
        precioCostoTexto.setName("precioTexto"); // NOI18N
        precioCostoTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioCostoTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioCostoTextoFocusLost(evt);
            }
        });
        precioCostoTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioCostoTextoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioCostoTextoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioCostoTextoKeyTyped(evt);
            }
        });

        gananciaTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        gananciaTexto.setText("0");
        gananciaTexto.setEnabled(false);
        gananciaTexto.setName("precioTexto"); // NOI18N
        gananciaTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gananciaTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gananciaTextoFocusLost(evt);
            }
        });
        gananciaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gananciaTextoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gananciaTextoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gananciaTextoKeyTyped(evt);
            }
        });

        ivaTexto.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        ivaTexto.setText("0");
        ivaTexto.setEnabled(false);
        ivaTexto.setName("precioTexto"); // NOI18N
        ivaTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ivaTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ivaTextoFocusLost(evt);
            }
        });
        ivaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ivaTextoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ivaTextoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ivaTextoKeyTyped(evt);
            }
        });

        eliminarBoton.setText("Eliminar");
        eliminarBoton.setEnabled(false);
        eliminarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarBotonMouseClicked(evt);
            }
        });
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(precioCostoTexto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel32)
                                    .addComponent(gananciaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(ivaTexto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ivaPorcentajeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gananciaPorcentajeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(0, 185, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productoTexto)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33)
                            .addComponent(jLabel35)
                            .addComponent(codigoTexto)
                            .addComponent(cantidadTexto)
                            .addComponent(cantidadMinTexto)
                            .addComponent(precioTexto)
                            .addComponent(precioBolivarTexto)
                            .addComponent(comboDepartamentos, 0, 310, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(eliminarBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guardarBoton))
                            .addComponent(editarBoton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadMinTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(precioCostoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gananciaPorcentajeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ivaPorcentajeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gananciaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ivaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(3, 3, 3)
                        .addComponent(precioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioBolivarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productoTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productoTextoKeyPressed
        pasarEnfoque(productoTexto, evt);
    }//GEN-LAST:event_productoTextoKeyPressed

    private void codigoTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_codigoTextoFocusGained

    private void codigoTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoTextoFocusLost

        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_codigoTextoFocusLost

    private void codigoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextoActionPerformed

    private void codigoTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextoKeyPressed
        pasarEnfoque(codigoTexto, evt);
    }//GEN-LAST:event_codigoTextoKeyPressed

    private void codigoTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTextoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_codigoTextoKeyTyped

    private void cantidadTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_cantidadTextoFocusGained

    private void cantidadTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadTextoFocusLost
        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_cantidadTextoFocusLost

    private void cantidadTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTextoActionPerformed

    private void cantidadTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTextoKeyPressed
        pasarEnfoque(cantidadTexto, evt);
    }//GEN-LAST:event_cantidadTextoKeyPressed

    private void cantidadTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTextoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_cantidadTextoKeyTyped

    private void cantidadMinTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadMinTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_cantidadMinTextoFocusGained

    private void cantidadMinTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadMinTextoFocusLost
        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_cantidadMinTextoFocusLost

    private void cantidadMinTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadMinTextoKeyPressed
        pasarEnfoque(cantidadMinTexto, evt);
    }//GEN-LAST:event_cantidadMinTextoKeyPressed

    private void cantidadMinTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadMinTextoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_cantidadMinTextoKeyTyped

    private void precioTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_precioTextoFocusGained

    private void precioTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioTextoFocusLost
        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_precioTextoFocusLost

    private void precioTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioTextoKeyPressed
        pasarEnfoque(precioTexto, evt);
    }//GEN-LAST:event_precioTextoKeyPressed

    private void precioTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioTextoKeyReleased
//        precioTextoModificar();
    }//GEN-LAST:event_precioTextoKeyReleased

    private void precioTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioTextoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_precioTextoKeyTyped

    private void precioBolivarTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioBolivarTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_precioBolivarTextoFocusGained

    private void precioBolivarTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioBolivarTextoFocusLost
        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_precioBolivarTextoFocusLost

    private void precioBolivarTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioBolivarTextoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_precioBolivarTextoMouseClicked

    private void precioBolivarTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioBolivarTextoKeyPressed
        pasarEnfoque(precioTexto,evt);
    }//GEN-LAST:event_precioBolivarTextoKeyPressed

    private void precioBolivarTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioBolivarTextoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_precioBolivarTextoKeyTyped

    private void editarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBotonActionPerformed
        
    }//GEN-LAST:event_editarBotonActionPerformed

    private void editarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBotonMouseClicked
        productoTexto.setEnabled(true);
        cantidadMinTexto.setEnabled(true);
        precioCostoTexto.setEnabled(true);
        precioTexto.setEnabled(true);
        gananciaTexto.setEnabled(true);
        ivaTexto.setEnabled(true);
        comboDepartamentos.setEnabled(true);
        guardarBoton.setEnabled(true);
        gananciaPorcentajeTexto.setEnabled(true);
        ivaPorcentajeTexto.setEnabled(true);
        eliminarBoton.setEnabled(true);
        editarBoton.setVisible(false);
        
    }//GEN-LAST:event_editarBotonMouseClicked

    private void guardarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBotonMouseClicked

    }//GEN-LAST:event_guardarBotonMouseClicked

    private void guardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotonActionPerformed
        ProductosBD productoBD = new ProductosBD(conexion);
        producto.setNombre(productoTexto.getText());
        producto.setCantidad(Integer.parseInt(cantidadTexto.getText()));
        producto.setCantidadMin(Integer.parseInt(cantidadMinTexto.getText()));
        producto.setPrecioCosto(Float.parseFloat(precioCostoTexto.getText()));
        producto.setGanancia(Float.parseFloat(gananciaPorcentajeTexto.getText()));
        producto.setIva(Float.parseFloat(ivaPorcentajeTexto.getText()));
        productoBD.updateProducto(producto);
        dispose();
    }//GEN-LAST:event_guardarBotonActionPerformed

    private void gananciaPorcentajeTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gananciaPorcentajeTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_gananciaPorcentajeTextoFocusGained

    private void gananciaPorcentajeTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gananciaPorcentajeTextoFocusLost
        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_gananciaPorcentajeTextoFocusLost

    private void gananciaPorcentajeTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gananciaPorcentajeTextoKeyPressed
        pasarEnfoque(gananciaPorcentajeTexto, evt);
    }//GEN-LAST:event_gananciaPorcentajeTextoKeyPressed

    private void gananciaPorcentajeTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gananciaPorcentajeTextoKeyReleased
//        calcularGanancia();
    }//GEN-LAST:event_gananciaPorcentajeTextoKeyReleased

    private void gananciaPorcentajeTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gananciaPorcentajeTextoKeyTyped
//        porcentajeNumero(evt);
    }//GEN-LAST:event_gananciaPorcentajeTextoKeyTyped

    private void ivaPorcentajeTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ivaPorcentajeTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_ivaPorcentajeTextoFocusGained

    private void ivaPorcentajeTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ivaPorcentajeTextoFocusLost
        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_ivaPorcentajeTextoFocusLost

    private void ivaPorcentajeTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivaPorcentajeTextoKeyPressed
        pasarEnfoque(ivaPorcentajeTexto, evt);
    }//GEN-LAST:event_ivaPorcentajeTextoKeyPressed

    private void ivaPorcentajeTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivaPorcentajeTextoKeyReleased
//        calcularIva();
    }//GEN-LAST:event_ivaPorcentajeTextoKeyReleased

    private void ivaPorcentajeTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivaPorcentajeTextoKeyTyped
//        porcentajeNumero(evt);
    }//GEN-LAST:event_ivaPorcentajeTextoKeyTyped

    private void precioCostoTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioCostoTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_precioCostoTextoFocusGained

    private void precioCostoTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioCostoTextoFocusLost
        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_precioCostoTextoFocusLost

    private void precioCostoTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioCostoTextoKeyPressed
        pasarEnfoque(precioCostoTexto, evt);
    }//GEN-LAST:event_precioCostoTextoKeyPressed

    private void precioCostoTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioCostoTextoKeyReleased
        precioCostoCalculo();
    }//GEN-LAST:event_precioCostoTextoKeyReleased

    private void precioCostoTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioCostoTextoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_precioCostoTextoKeyTyped

    private void gananciaTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gananciaTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_gananciaTextoFocusGained

    private void gananciaTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gananciaTextoFocusLost
        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_gananciaTextoFocusLost

    private void gananciaTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gananciaTextoKeyPressed
        pasarEnfoque(gananciaTexto, evt);
    }//GEN-LAST:event_gananciaTextoKeyPressed

    private void gananciaTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gananciaTextoKeyReleased
        calcularPorcentajeGanancia();
    }//GEN-LAST:event_gananciaTextoKeyReleased

    private void gananciaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gananciaTextoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_gananciaTextoKeyTyped

    private void ivaTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ivaTextoFocusGained
        quitarTexto(evt.getComponent());
    }//GEN-LAST:event_ivaTextoFocusGained

    private void ivaTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ivaTextoFocusLost
        ponerTexto(evt.getComponent());
    }//GEN-LAST:event_ivaTextoFocusLost

    private void ivaTextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivaTextoKeyPressed
        pasarEnfoque(ivaTexto, evt);
    }//GEN-LAST:event_ivaTextoKeyPressed

    private void ivaTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivaTextoKeyReleased
        calcularPorcentajeIva();
    }//GEN-LAST:event_ivaTextoKeyReleased

    private void ivaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ivaTextoKeyTyped
        soloNumeros(evt);
    }//GEN-LAST:event_ivaTextoKeyTyped

    private void eliminarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBotonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBotonMouseClicked

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        ProductosBD productoBD = new ProductosBD(conexion);
        productoBD.eliminarProductos(codigo);
        JOptionPane.showMessageDialog(null, "El producto se ha eliminado con éxito");
        dispose();
    }//GEN-LAST:event_eliminarBotonActionPerformed

    /**
     * @param con
     * @param codigoProducto
     */
    public static void crearVentana(Connection con, String codigoProducto, ObtenerParametros parametros) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new InformacionProducto(con, codigoProducto,parametros ).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(InformacionProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    public void cargarProducto() throws SQLException{
        ProductosBD productos;
        productos = new ProductosBD(conexion);
        producto = productos.getProducto(codigo);
        float precio = producto.getPrecioCosto()+ (producto.getPrecioCosto()*producto.getIva())/100 
                + (producto.getPrecioCosto()*producto.getGanancia()/100);
        productoTexto.setText(producto.getNombre());
        codigoTexto.setText(producto.getCodigo());
        cantidadTexto.setText(String.valueOf( producto.getCantidad()));
        cantidadMinTexto.setText(String.valueOf(producto.getCantidadMin()));
        precioCostoTexto.setText(String.valueOf(producto.getPrecioCosto()));
        precioTexto.setText(String.valueOf(precio));
        gananciaTexto.setText(String.valueOf((producto.getPrecioCosto()*producto.getGanancia()/100)));
        ivaTexto.setText(redondear(((producto.getPrecioCosto()+producto.getPrecioCosto()*producto.getGanancia()/100)*producto.getIva())/100 ));
        comboDepartamentos.addItem(departamento.getNombreDepartamento(producto.getDepartamento()));
        System.out.println(producto.getRif());
        gananciaPorcentajeTexto.setText(String.valueOf(producto.getGanancia()));
        ivaPorcentajeTexto.setText(String.valueOf(producto.getIva()));
        precioBolivarTexto.setText(redondear(precio * parametros.getTasa()));
        
        
    }
    
    
    

    public void quitarTexto(Component componente){
        JTextField cajaTexto = (JTextField) componente;
        if (cajaTexto.getText().equals("0") || cajaTexto.getText().equals("0.0")){
            cajaTexto.setText(null);
        }
        
    }
    
    private void pasarEnfoque(Component siguiente, java.awt.event.KeyEvent evt ){
        int key = evt.getKeyCode();
        boolean enter = key == 10;
        boolean flechaAbajo = key == 40;
        boolean flechaArriba = key == 38;
        
        if ((enter || flechaAbajo)){
            siguiente.transferFocus();
        }
        if (flechaArriba){
            siguiente.transferFocusBackward();
        }
    }
            //pone el texto predeterminado en los textbox vacios cuando pierden el foco
    public void ponerTexto(Component componente){
        JTextField cajaTexto = (JTextField) componente;
        if (cajaTexto.getText().equals("")){
            cajaTexto.setText("0");
        }
    }
    
    //solo permite ingresar numeros en los textBox
    private void soloNumeros(java.awt.event.KeyEvent evt){
        JTextField cajaTexto = (JTextField)evt.getComponent();
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean punto = key == 46;
        boolean borrar = key == 8;
        boolean enter = key == 10;
        if (!(numeros || punto || borrar))
        {
            evt.consume();
        }
        if (cajaTexto.getText().trim().length() == 20 && !(borrar)) {
            evt.consume();
        }
    }
    
    private void porcentajeNumero(java.awt.event.KeyEvent evt){
        JTextField cajaTexto = (JTextField)evt.getComponent();
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        boolean borrar = key == 8;
        if (!(numeros || borrar))
        {
            evt.consume();
        }
        if (cajaTexto.getText().trim().length() == 4 && !(borrar)) {
            evt.consume();
        }
    }
    
    private void calcularPorcentajeGanancia()
    {
        try{
            double precioCosto = Double.parseDouble(precioCostoTexto.getText());
            double ganancia = Double.parseDouble(gananciaTexto.getText());
            if(precioCosto > 0){
                String porcentajeGanancia = redondear(ganancia/precioCosto*100);
                gananciaPorcentajeTexto.setText(porcentajeGanancia);
                actualizarPrecioFinal();
                gananciaUltimo = true;
            }    
        }
        catch(Exception e){
            gananciaPorcentajeTexto.setText("0");
        }
        
    }
    
    private void calcularGanancia()
    {  
        
        try{
            double precioCosto = Double.parseDouble(precioCostoTexto.getText());
            double gananciaPorcentaje = Double.parseDouble(gananciaPorcentajeTexto.getText());
            String Ganancia = redondear(precioCosto*gananciaPorcentaje/100);
            gananciaTexto.setText(Ganancia);
            actualizarPrecioFinal();
            gananciaUltimo = false;
        }
        catch(NumberFormatException e){
            gananciaTexto.setText("0");
        }
    }
    
    private void calcularPorcentajeIva()
    {
        try{
            double precioCosto = Double.parseDouble(precioCostoTexto.getText());
            double ganancia = Double.parseDouble(gananciaTexto.getText());
            double iva = Double.parseDouble(ivaTexto.getText());
            if (precioCosto > 0){
                String porcentajeIva =redondear(iva/(precioCosto+ganancia)*100);
                ivaPorcentajeTexto.setText(porcentajeIva);
                actualizarPrecioFinal();
                ivaUltimo = true;
            }
                    
        }
        catch(Exception e){
            ivaPorcentajeTexto.setText("0");
        }
        
    }
    
    private void calcularIva()
    {
        try{
            double precioCosto = Double.parseDouble(precioCostoTexto.getText());
            double ganancia = Double.parseDouble(gananciaTexto.getText());
            double ivaPorcentaje = Double.parseDouble(ivaPorcentajeTexto.getText());
            String iva = redondear((precioCosto+ganancia)*ivaPorcentaje/100);
            ivaTexto.setText(iva);
            actualizarPrecioFinal();
            ivaUltimo = false;
        }
        catch(NumberFormatException e){
            ivaTexto.setText("0");
        }    
    }
    
    private void actualizarPrecioFinal()
    {
        double precioFinal;
        try
        {
            precioFinal = Double.parseDouble(precioCostoTexto.getText()) + 
            Double.parseDouble(gananciaTexto.getText()) + Double.parseDouble(ivaTexto.getText());
            precioTexto.setText(redondear(precioFinal));
            precioFinalUltimo = precioFinal;
            precioBs();
        }
        catch(NumberFormatException e){
            
        }
    }
    
    private void precioBs(){
        double precioFinal = Double.parseDouble(precioTexto.getText());
        precioBolivarTexto.setText(redondear(precioFinal*parametros.getTasa()));   
    }
    private void precioCostoCalculo()
    {
        if(gananciaUltimo == true)
        {
            calcularPorcentajeGanancia();
        }
        else
        {
            calcularGanancia();
        }
        if(ivaUltimo == true)
        {
            calcularPorcentajeIva();
        }
        else
        {
            calcularIva();
        }
        actualizarPrecioFinal();
               
    }
    
    //recalcula los valores cuando el textBox de precio es modificado
    private void precioTextoModificar()
    {
        try{
            double precioFinal = Double.parseDouble(precioTexto.getText());
            double diferencia = precioFinal - precioFinalUltimo;
            double ganancia = Double.parseDouble(gananciaTexto.getText());
            String nuevaGanancia = String.valueOf(diferencia + ganancia);
            gananciaTexto.setText(nuevaGanancia);
            calcularPorcentajeGanancia();
        }
        catch(NumberFormatException e)
        {
        
            System.out.println("error " + e.getMessage());}
    }
    
    private String redondear(double numero){
        int decimales = 2;
        String resultado;
        BigDecimal bd = new BigDecimal(numero);
        bd = bd.setScale(decimales, RoundingMode.HALF_UP);
        resultado = bd.toString();
        return resultado;
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadMinTexto;
    private javax.swing.JTextField cantidadTexto;
    private javax.swing.JTextField codigoTexto;
    private javax.swing.JComboBox<String> comboDepartamentos;
    private javax.swing.JButton editarBoton;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JTextField gananciaPorcentajeTexto;
    private javax.swing.JTextField gananciaTexto;
    private javax.swing.JButton guardarBoton;
    private javax.swing.JTextField ivaPorcentajeTexto;
    private javax.swing.JTextField ivaTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField precioBolivarTexto;
    private javax.swing.JTextField precioCostoTexto;
    private javax.swing.JTextField precioTexto;
    private javax.swing.JTextField productoTexto;
    // End of variables declaration//GEN-END:variables
}
